articles/urls.py
from django.urls import path

from . import  views

app_name = 'articles'
urlpatterns = [
    path('', views.index, name = 'home'),
    path('add_article/', views.add_article, name = 'add_article'),
    path('ajax_add_comment/', views.ajax_add_comment, name = 'ajax_add_comment'),
    path('ajax_check_comment/', views.ajax_check_comment, name = 'ajax_check_comment'),
    path('<int:article_id>/', views.detail, name= 'detail'),
]

docker/djangodocker/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('polls/', include('polls.urls')),
    path('admin/', admin.site.urls),
]

interview_site/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('articles.urls')),
    path('admin/', admin.site.urls),
]

articles/models.py
from django.db import models

# Create your models here.


class Article(models.Model):
    title = models.CharField('Название статьи', max_length= 100)
    text = models.TextField('Текст статьи')
    pub_date = models.DateTimeField('Дата публикации')

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Статья'
        verbose_name_plural = 'Статьи'

class Comment(models.Model):

    article = models.ForeignKey(Article, on_delete= models.CASCADE)


    parents_id = models.CharField('Родители комментария',max_length= 200)
    # path = ArrayField(models.IntegerField)  #Для PostgeSQL
    active = models.BooleanField(default=True)
    author_name = models.CharField('Имя автора', max_length= 50, unique=True)
    text = models.CharField('Текст комментария', max_length= 200)


    def __str__(self):
        return self.author_name

    class Meta:
        verbose_name = 'Комментарии'
        verbose_name_plural = 'Комментарии'

articles/forms.py
from .models import Article
from django.forms import ModelForm, Textarea, TextInput

class ArticleForm(ModelForm):
    class Meta:
        model = Article
        fields = ['title', 'text', 'pub_date']

        widgets = {

            "title" : TextInput(attrs={
                'class': 'form_control',
                'placeholder': 'Введите название'
            }),
            "text": Textarea(attrs={
                  'class' : 'form_control',
                  'placeholder' : 'Введите описание'
            }),

        }

articles/views.py
from django.http import  HttpResponse, Http404, HttpResponseRedirect, JsonResponse
from django.shortcuts import render, redirect
from .models import Article, Comment
from .forms import ArticleForm
from django.utils import timezone
from django.core.paginator import Paginator

def index(request):        #Выводиь все статьи
    latest_articles_list = Article.objects.order_by('-pub_date')

    paginator = Paginator(latest_articles_list, 5)   # в одной странице 5 статьей

    page_number = request.GET.get('page')  # при нажатии на кнопку выбора страниц, гет запросов получаем обратно, для начала будет 1
    post = paginator.get_page(page_number)
    return render(request, 'list.html', {'latest_articles_list' : post})

def add_article(request):
    error = ""
    if request.method == "POST":
        new_article = Article()
        new_article.title = request.POST['title']
        new_article.text = request.POST['text']
        new_article.pub_date = timezone.now()
        new_article.pub_date = timezone.now()
        new_article.save()
        return redirect('articles:home')


    form_article = ArticleForm()        #форма ввода статьи


    return render(request, 'addarticle.html', {'form_article' : form_article, 'error': error })


def create_api(parent, childs, end_number, strart_num):  #рекурсивная функция, построения дерева, для отправку клиенту комментарии
    dictionory_number_level ={}
    dictionory_number_level['parent'] = parent
    if end_number == strart_num:      # уровень вложенности рекурсивной функции, который нам необходим
        dictionory_number_level['child'] = None
        return dictionory_number_level

    all_child_comment = []

    for child in childs:
        child = comment_to_dictionary(child)
        child = create_api(child, childs, end_number, strart_num + 1)  #ищем дочерние дочерних комментариев
        if (int(parent['id']) == int(child['parent']['parent_id'])):
            all_child_comment.append(child)


    if len(all_child_comment) == 0:
        dictionory_number_level['child'] = None
    else:
        dictionory_number_level['child'] = all_child_comment


    return dictionory_number_level      #возвращаем словарь, вида {parent: 'Not None', child: 'None'} or
                                    # {parent: 'Not None', child: [{parent:'not None(это child}', child:"not None"}]}   or
            # {parent: 'Not None', child: [{parent:'not None(это child}', child: [{parent:'not None(это child}', child:"not None"}]}]}


def detail(request, article_id):      # вывод статьи с комментариями
    try:
        a = Article.objects.get(id = article_id)
    except:
        raise Http404("Статья не найдена!")
    latest_comments_list = a.comment_set.filter(active=True).order_by('-id') #комментарии родительские, с последнего

    latest_comments_comments_list = a.comment_set.filter(active=False).order_by('id') #все дочерние комментарии

    all_comment = []

    for comment in latest_comments_list:
        comment = comment_to_dictionary(comment)    #Query делаем в словарь(dict)
        comment = create_api(comment, latest_comments_comments_list, 4, 1)
        all_comment.append(comment)

    paginator = Paginator(all_comment, 5)     #Полученный весь список, с словарями, оборачиваем в пагинатор, первые 5

    page_number = request.GET.get('page')
    post = paginator.get_page(page_number)

    return render(request, 'detail.html', {'article' : a, 'all_comment' : post })

def comment_to_dictionary(model_comment_object):
    if model_comment_object == None:
        return None

    dictionary = {}
    dictionary["id"] = model_comment_object.id
    dictionary["author_name"] = model_comment_object.author_name
    dictionary["text"] = model_comment_object.text
    dictionary["parent_id"] = model_comment_object.parents_id
    dictionary["article_id"] = model_comment_object.article.id

    return dictionary


def ajax_check_comment(request):   #Запрос для просмотра ответов комментариев, 4 уровня и выше
    result = {}
    parent_id = str(request.POST['parent_id'])

    try:
        childs_comment = Comment.objects.filter(parents_id = parent_id)
        all_childs_comment = Comment.objects.filter(active=False)
        all_comment_child = []

        for child in childs_comment:
            child= comment_to_dictionary(child)
            child = create_api(child, all_childs_comment, 2, 1) #нужен подвинуть уровень вложенности комментариев, на одну
            all_comment_child.append(child)

        result['code'] = 10000
        result['content'] = all_comment_child
        result['child'] = 'No' # Для комментариев 4 уровня и выше, в будущем нужен.

    except:
        result['code'] = 10002
        result['content'] = 'Параметр запроса пуст'

    return JsonResponse(result)


def ajax_add_comment(request):     # Для добавления комментариев
    result = {}
    username = request.POST['username']
    text = request.POST['text']
    article_id = request.POST['article_id']
    parent_id = request.POST['parent_id']
    if len(username) ==0 or len(text) ==0:
        result['code'] = 10002
        result['content'] = 'Параметр запроса пуст'
    else:
        try:
            if(parent_id == ''):  #Добавлегие комментария 1 уровня
                a = Article.objects.get(id = article_id)
                a.comment_set.create(author_name= username, text = text)
                latest_comment = a.comment_set.get(author_name= username, text = text)

                result['parents_id'] = latest_comment.id
                result['id'] = (latest_comment.id)
            else:  #Добавлегие 2 и выще

                a = Article.objects.get(id = article_id)
                a.comment_set.create(author_name= username, text = text, parents_id= parent_id, active= False)
                latest_comment = a.comment_set.get(author_name= username, text = text)

                result['parents_id'] = str(latest_comment.parents_id)
                result['id'] = (latest_comment.id)

            result['code'] = 10000
            result['content'] = 'Успешно добавленные данные'

        except:
            result['code'] = 10002
            result['content'] = 'Ошибка добавления данных'

    return JsonResponse(result)

articles/templates/addarticle.html
{% extends 'base.html' %}

{% block title %}Добавление статьи{% endblock %}

{% block content%}
<a  class="new_article" href="{% url 'articles:home'  %}" > <button type="button">Назад</button></a>
<h1>Добавление Статьи</h1>
<br>
{{ error }}
<form  method="POST">
    {% csrf_token %}
    {{ form_article.title }}
    <br>
    {{ form_article.text }}
    <br>
    <button type="submit">Добавить статью</button>
    <br>
</form>

{% endblock %}

articles/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %} Мой сайт {% endblock %}</title>
    {% load static %}
    <link type="text/css" href="{% static 'articles/css/style.css' %}" rel="stylesheet" />
    <script type="text/javascript" src="{% static 'articles/js/jquery-3.6.0.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'articles/js/detail.js' %}"></script>
<!--    {% load static %}-->
<!--    &lt;!&ndash;<link type="text/css" href="{% static 'main/css/styles.css' %}" rel="stylesheet" />&ndash;&gt;-->
<!--    <script type="text/javascript" src="{% static 'articles/js/jquery-3.6.0.min.js' %}"></script>-->
</head>
<body>
    {% block content %}{% endblock %}

</body>

</html>

articles/templates/detail.html
{% extends 'base.html' %}

{% block title %} {{article.title}} {% endblock %}

{% block content%}
<a  class="new_article" href="{% url 'articles:home'  %}" > <button type="button">Назад</button></a>
<div class="article_id" value="{{ article.id }}"></div><h2>{{ article.title }}</h2>

<p>{{ article.text }}</p>

<em>{{ article.pub_date }}</em>

<hr>
<div class="comments" id="comments">
{% if all_comment %}
    {% for c_1 in all_comment %}
        <div class = "comment_1" name= "comment" value = '{{ c_1.parent.id }}' >


                <em>Комментатор: </em><strong>{{ c_1.parent.author_name }}</strong>
                <p> {{ c_1.parent.text }} </p>

                {% if c_1.child %}

                        {% for c_2 in c_1.child %}
                            <div class="comment_2" name="comment_2" value="{{ c_2.parent.id }}"  hidden>

                                    <em>Комментатор: </em><strong>{{ c_2.parent.author_name }}</strong>
                                    <p> {{ c_2.parent.text }} </p>

        <!--                                <div answer анадлш-->
                                        {% if c_2.child %}

                                                {% for c_3 in c_2.child %}
                                                    <div class="comment_3" name="comment_3" value="{{ c_3.parent.id }}"  hidden >

                                                            <em>Комментатор: </em><strong>{{ c_3.parent.author_name }}</strong>
                                                            <p> {{ c_3.text }} </p>
                                                            <div id="answer{{ c_3.parent.id }}"  hidden>

                                                                <form action='' method="POST">
                                                                    {% csrf_token %}

                                                                    <input type="text" id="add_name_comment_4_{{ c_3.parent.id }}" required placeholder="Ваше имя" name="name"><br>
                                                                    <textarea  name="text" id='add_text_comment_4_{{ c_3.parent.id }}' required="" placeholder="Текст комментрия" cols="30" rows="10"></textarea><br>
                                                                    <input type="button" id=4 class="sent_button_comment" value="Оставить комментраий" >  </input>
                                <!--                                    <input type="button" class="sent_button_comment" value="Ответить" id = '{{ x.parent.id }}'>  </input>-->

                                                                </form>


                                                            </div>

                                                            <button type="button" class = "answer_button" value="{{ c_3.parent.id }}" >Ответить</button>
                                                            <button type="button" class = "cansel_button" value="{{ c_3.parent.id }}" hidden >Отмена</button>
                                                            {% if c_3.child %}
                                                                <button name=""  type="button" class = "answer_show_button" value="4" >Посмотреть ответы</button>
                                                                <button name=""  type="button" class = "answer_close_button" value="4" hidden>Закрыть</button>
                                                            {% endif %}
                                                        <br>

                                                         <br>
                                                    </div>
                                                {% endfor %}
                                        {% endif %}
                                    <div id="answer{{ c_2.parent.id }}"  hidden>

                                        <form action='' method="POST">
                                            {% csrf_token %}

                                            <input type="text" id="add_name_comment_3_{{ c_2.parent.id }}" required placeholder="Ваше имя" name="name"><br>
                                            <textarea  name="text" id='add_text_comment_3_{{ c_2.parent.id }}' required="" placeholder="Текст комментрия" cols="30" rows="10"></textarea><br>
                                            <input type="button" id=3 class="sent_button_comment" value="Оставить комментраий" >  </input>

                                        </form>


                                    </div>

                                    <button type="button" class = "answer_button" value="{{ c_2.parent.id }}" >Ответить</button>
                                    <button type="button" class = "cansel_button" value="{{ c_2.parent.id }}" hidden >Отмена</button>
                                    {% if c_2.child %}
                                        <button name="created"  type="button" class = "answer_show_button" value="3" >Посмотреть ответы</button>
                                        <button name="created"  type="button" class = "answer_close_button" value="3" hidden>Закрыть</button>
                                    {% endif %}

                                <br>
                                 <br>
                            </div>
                        {% endfor %}
                {% endif %}
                <div id="answer{{ c_1.parent.id }}"  hidden>

                    <form action='' method="POST">
                        {% csrf_token %}

                        <input type="text" id="add_name_comment_2_{{ c_1.parent.id }}" required placeholder="Ваше имя" name="name"><br>
                        <textarea  name="text" id='add_text_comment_2_{{ c_1.parent.id }}' required="" placeholder="Текст комментрия" cols="30" rows="10"></textarea><br>
                        <input type="button" id=2 class="sent_button_comment" value="Оставить комментраий" >  </input>

                    </form>


                </div>

                <button type="button" class = "answer_button" value="{{ c_1.parent.id }}" >Ответить</button>
                <button type="button" class="cansel_button" value="{{ c_1.parent.id }}" hidden >Отмена</button>
                {% if c_1.child %}
                    <button name="created"  type="button" class = "answer_show_button" value="2" >Посмотреть ответы</button>
                    <button name="created"  type="button" class = "answer_close_button"  value="2" hidden>Закрыть</button>
                {% endif %}

            <br>
            <br>
        </div>
    {% endfor %}


        <nav class='list-pages'>
            <ul>
                {% for p in all_comment.paginator.page_range %}
                <li class='page-num'>
                    <a href="?page={{ p }}">{{ p }}</a>
                </li>
                {% endfor %}
            </ul>
        </nav>



{% else %}
    Комментарии не найдены, станьте первым!
{% endif %}
</div>
<hr>
<div class="check_comment_url" value="{% url 'articles:ajax_check_comment' %}"></div>
<div class="add_comment_url" value="{% url 'articles:ajax_add_comment' %}"></div>
<div id="add_comment" >
    <form action='' method="POST">
        {% csrf_token %}

        <input type="text" id = 'add_name_comment_1' required placeholder="Ваше имя" name="name"><br>
        <textarea  name="text" id = 'add_text_comment_1' required="" placeholder="Текст комментрия" cols="30" rows="10"></textarea><br>
        <input type="button" id=1 class="sent_button_comment" value="Оставить комментраий"> </input>

    </form>
</div>





{% endblock %}

articles/templates/list.html
{% extends 'base.html' %}

{% block title %}Последние статьи{% endblock %}

{% block content%}

    {% if latest_articles_list %}
        {% for a in latest_articles_list %}
            <h2>Статья: {{a.title}}</h2>
            <a href="{% url 'articles:detail' a.id %}"><button type="button">Перейти к статьте</button> </a>
            <br>
        {% endfor %}

        <nav class='list-pages'>
            <ul>
                {% for p in latest_articles_list.paginator.page_range %}
                <li class='page-num'>
                    <a href="?page={{ p }}">{{ p }}</a>
                </li>
                {% endfor %}
            </ul>
        </nav>
    {% else %}
        Статьи не найдены
    {% endif %}
<br>
<br>
<a  class="new_article" href="{% url 'articles:add_article'  %}" > <button type="button"> Добавить новую статью</button></a>




{% endblock %}